/*
 * @file mkpp_c_api.cpp
 * @brief C ABI Wrapper Implementation for MKPP Mechanism: ts1
 *
 * Generated by MKPP AOT Compiler - DO NOT EDIT DIRECTLY.
 */

#include "mkpp.h"
#include "mkpp_host/dispatcher.hpp"
#include "ts1.hpp"

#include <cstring>
#include <string>
#include <unordered_map>
#include <vector>

using mkpp::mkpp_handle_impl;
using ExecSpace = Kokkos::DefaultExecutionSpace;
using SolverKernelsType = mkpp::SolverKernels<ExecSpace>;

namespace {

// Static species name map
static const std::unordered_map<std::string, int> SPECIES_NAME_MAP = {
    {"ALKNIT", 0},
    {"BZOOH", 1},
    {"C6H5OOH", 2},
    {"COF2", 3},
    {"O2", 4},
    {"COFCL", 5},
    {"HF", 6},
    {"F", 7},
    {"BENZO2", 8},
    {"BZOO", 9},
    {"N2", 10},
    {"E90", 11},
    {"NH_5", 12},
    {"NH_50", 13},
    {"ST80_25", 14},
    {"PAN", 15},
    {"MVK", 16},
    {"MACROOH", 17},
    {"SOAG0", 18},
    {"SOAG1", 19},
    {"SOAG2", 20},
    {"SOAG3", 21},
    {"SOAG4", 22},
    {"soa4_a1", 23},
    {"soa5_a1", 24},
    {"soa5_a2", 25},
    {"soa3_a1", 26},
    {"soa2_a1", 27},
    {"soa1_a1", 28},
    {"soa1_a2", 29},
    {"soa2_a2", 30},
    {"soa3_a2", 31},
    {"soa4_a2", 32},
    {"ISOPNITB", 33},
    {"SO3", 34},
    {"OCS", 35},
    {"SO", 36},
    {"S", 37},
    {"BCARYO2VBS", 38},
    {"SF6", 39},
    {"sink", 40},
    {"H", 41},
    {"MEK", 42},
    {"MTERP", 43},
    {"N2O5", 44},
    {"HCN", 45},
    {"SVOC", 46},
    {"ISOPNO3", 47},
    {"RO2", 48},
    {"PHENO2", 49},
    {"BENZO2VBS", 50},
    {"IVOC", 51},
    {"TERPNIT", 52},
    {"ISOPO2VBS", 53},
    {"IVOCO2VBS", 54},
    {"HNO3", 55},
    {"ACBZO2", 56},
    {"CH3COOOH", 57},
    {"SO2", 58},
    {"MTERPO2VBS", 59},
    {"CH4", 60},
    {"CH3CL", 61},
    {"CH3CO3", 62},
    {"C6H5O2", 63},
    {"TERPROD1", 64},
    {"HYAC", 65},
    {"HPALD", 66},
    {"TOLUO2VBS", 67},
    {"H2O", 68},
    {"NO2", 69},
    {"EOOH", 70},
    {"NTERPOOH", 71},
    {"XYLEO2VBS", 72},
    {"CCL4", 73},
    {"CF2CLBR", 74},
    {"CF3BR", 75},
    {"CFC11", 76},
    {"CFC113", 77},
    {"CFC114", 78},
    {"CFC115", 79},
    {"CFC12", 80},
    {"CH2BR2", 81},
    {"CH3BR", 82},
    {"CH3CCL3", 83},
    {"NO", 84},
    {"BR", 85},
    {"BRCL", 86},
    {"BRO", 87},
    {"BRONO2", 88},
    {"CL", 89},
    {"CL2", 90},
    {"CL2O2", 91},
    {"CLO", 92},
    {"CLONO2", 93},
    {"HCOOH", 94},
    {"HBR", 95},
    {"HOBR", 96},
    {"HOCL", 97},
    {"N", 98},
    {"BIGENE", 99},
    {"C2H4", 100},
    {"C2H5O2", 101},
    {"CH3COCHO", 102},
    {"CH3COCH3", 103},
    {"O", 104},
    {"OCLO", 105},
    {"O1D", 106},
    {"PHENO", 107},
    {"HCFC141B", 108},
    {"HCFC142B", 109},
    {"HCFC22", 110},
    {"DMS", 111},
    {"C2H5OH", 112},
    {"HCL", 113},
    {"BEPOMUC", 114},
    {"CHBR3", 115},
    {"H2402", 116},
    {"CO2", 117},
    {"BZALD", 118},
    {"BENZENE", 119},
    {"C3H7O2", 120},
    {"CH3O2", 121},
    {"BCARY", 122},
    {"BIGALD", 123},
    {"BIGALD2", 124},
    {"BIGALD3", 125},
    {"BIGALD4", 126},
    {"BIGALK", 127},
    {"H2O2", 128},
    {"C2H5OOH", 129},
    {"C2H6", 130},
    {"C3H8", 131},
    {"C3H6", 132},
    {"CH2O", 133},
    {"CH3CN", 134},
    {"C2H2", 135},
    {"CH3OH", 136},
    {"CH3OOH", 137},
    {"CRESOL", 138},
    {"ENEO2", 139},
    {"MACRO2", 140},
    {"ISOPAO2", 141},
    {"MALO2", 142},
    {"ISOPBO2", 143},
    {"MCO3", 144},
    {"MDIALO2", 145},
    {"MEKO2", 146},
    {"EO2", 147},
    {"EO", 148},
    {"GLYOXAL", 149},
    {"MPAN", 150},
    {"NC4CH2OH", 151},
    {"ISOPOOH", 152},
    {"GLYALD", 153},
    {"HO2", 154},
    {"HOCH2OO", 155},
    {"H2", 156},
    {"HYDRALD", 157},
    {"ISOP", 158},
    {"NTERPO2", 159},
    {"TOLO2", 160},
    {"TERP2O2", 161},
    {"XYLENO2", 162},
    {"TERPO2", 163},
    {"XYLOLO2", 164},
    {"PBZNIT", 165},
    {"XYLENES", 166},
    {"PO2", 167},
    {"TOLUENE", 168},
    {"XO2", 169},
    {"XOOH", 170},
    {"TERPROD2", 171},
    {"MEKOOH", 172},
    {"MACR", 173},
    {"HONITR", 174},
    {"ISOPNITA", 175},
    {"ISOPNOOH", 176},
    {"IEPOX", 177},
    {"ONITR", 178},
    {"H2SO4", 179},
    {"N2O", 180},
    {"NO3", 181},
    {"OH", 182},
    {"PHENOOH", 183},
    {"PHENOL", 184},
    {"XYLOL", 185},
    {"ROOH", 186},
    {"O3", 187},
    {"TERPOOH", 188},
    {"TOLOOH", 189},
    {"XYLENOOH", 190},
    {"XYLOLOOH", 191},
    {"CO", 192},
    {"CH3COOH", 193},
    {"CH3CHO", 194},
    {"BIGALD1", 195},
    {"ALKOOH", 196},
    {"DICARBO2", 197},
    {"BENZOOH", 198},
    {"ALKO2", 199},
    {"HO2NO2", 200},
    {"C3H7OOH", 201},
    {"NH3", 202},
    {"TERP2OOH", 203},
    {"POOH", 204},
    {"NOA", 205},
    {"NC4CHO", 206},
    {"TEPOMUC", 207},
    {"NH4", 208},
    {"M", 209},
};

// Static photolysis name map
static const std::unordered_map<std::string, int> PHOTOLYSIS_NAME_MAP = {
};

} // anonymous namespace

extern "C" {

int mkpp_create_handle(mkpp_handle_t* handle_out, size_t num_cells) {
    if (!handle_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    if (num_cells == 0) {
        return MKPP_ERROR_INVALID_ARGUMENT;
    }

    try {
        auto* handle = new mkpp_handle_impl();
        handle->num_cells = num_cells;
        handle->num_species = 210;
        handle->num_reactions = 547;
        handle->num_photolysis = 0;
        handle->is_initialized = false;
        *handle_out = reinterpret_cast<mkpp_handle_t>(handle);
        return MKPP_SUCCESS;
    } catch (const std::exception& e) {
        return MKPP_ERROR_INVALID_STATE;
    }
}

int mkpp_destroy_handle(mkpp_handle_t handle) {
    if (!handle) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    delete impl;
    return MKPP_SUCCESS;
}

int mkpp_initialize(mkpp_handle_t handle) {
    if (!handle) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);

    try {
        // Allocate internal scratch workspace (num_cells, num_species + num_reactions)
        std::size_t scratch_cols = impl->num_species + impl->num_reactions + 16;
        impl->workspace_scratch = Kokkos::View<double**, Kokkos::LayoutLeft>(
            "mkpp_scratch_workspace", impl->num_cells, scratch_cols);
        impl->is_initialized = true;
        return MKPP_SUCCESS;
    } catch (const std::exception& e) {
        impl->set_error(e.what());
        return MKPP_ERROR_INVALID_STATE;
    }
}

int mkpp_get_species_count(mkpp_handle_t handle, size_t* count_out) {
    if (!handle || !count_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    *count_out = impl->num_species;
    return MKPP_SUCCESS;
}

int mkpp_get_reaction_count(mkpp_handle_t handle, size_t* count_out) {
    if (!handle || !count_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    *count_out = impl->num_reactions;
    return MKPP_SUCCESS;
}

int mkpp_get_photolysis_count(mkpp_handle_t handle, size_t* count_out) {
    if (!handle || !count_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    *count_out = impl->num_photolysis;
    return MKPP_SUCCESS;
}

int mkpp_get_species_index(mkpp_handle_t handle, const char* species_name, int* index_out) {
    if (!handle || !species_name || !index_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto it = SPECIES_NAME_MAP.find(species_name);
    if (it != SPECIES_NAME_MAP.end()) {
        *index_out = it->second;
        return MKPP_SUCCESS;
    }
    *index_out = -1;
    return MKPP_ERROR_NOT_FOUND;
}

int mkpp_get_photolysis_index(mkpp_handle_t handle, const char* photo_name, int* index_out) {
    if (!handle || !photo_name || !index_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto it = PHOTOLYSIS_NAME_MAP.find(photo_name);
    if (it != PHOTOLYSIS_NAME_MAP.end()) {
        *index_out = it->second;
        return MKPP_SUCCESS;
    }
    *index_out = -1;
    return MKPP_ERROR_NOT_FOUND;
}

int mkpp_set_state_ptrs(mkpp_handle_t handle,
                        double* species_conc,
                        const double* temp,
                        const double* pressure,
                        const double* air_density) {
    if (!handle || !species_conc || !temp || !pressure || !air_density) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);

    impl->species_conc = Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged>(
        species_conc, impl->num_cells, impl->num_species);

    impl->temperature = Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged>(
        const_cast<double*>(temp), impl->num_cells);

    impl->pressure = Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged>(
        const_cast<double*>(pressure), impl->num_cells);

    impl->air_density = Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged>(
        const_cast<double*>(air_density), impl->num_cells);

    return MKPP_SUCCESS;
}

int mkpp_set_photolysis_ptrs(mkpp_handle_t handle, const double* photolysis_rates) {
    if (!handle || !photolysis_rates) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);

    if (impl->num_photolysis > 0) {
        impl->photolysis_rates = Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged>(
            const_cast<double*>(photolysis_rates), impl->num_cells, impl->num_photolysis);
    }
    return MKPP_SUCCESS;
}

int mkpp_set_aerosol_ptrs(mkpp_handle_t handle,
                         const double* relative_humidity,
                         const double* aerosol_surface_area) {
    if (!handle) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);

    if (relative_humidity) {
        impl->relative_humidity = Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged>(
            const_cast<double*>(relative_humidity), impl->num_cells);
    }
    if (aerosol_surface_area) {
        impl->aerosol_surface_area = Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged>(
            const_cast<double*>(aerosol_surface_area), impl->num_cells);
    }
    return MKPP_SUCCESS;
}

int mkpp_integrate(mkpp_handle_t handle, double dt) {
    if (!handle) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    if (!impl->is_initialized) {
        return MKPP_ERROR_INVALID_STATE;
    }
    if (!impl->species_conc.data()) {
        return MKPP_ERROR_NULL_POINTER;
    }

    try {
        const double* jvals = impl->photolysis_rates.data();
        mkpp::host::execute_mechanism<SolverKernelsType>(
            "ts1", impl->species_conc, dt, jvals);
        return MKPP_SUCCESS;
    } catch (const std::exception& e) {
        impl->set_error(e.what());
        return MKPP_ERROR_CONVERGENCE;
    }
}

int mkpp_evaluate_rates(mkpp_handle_t handle, double* rates_out) {
    if (!handle || !rates_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    if (!impl->is_initialized) {
        return MKPP_ERROR_INVALID_STATE;
    }
    if (!impl->species_conc.data()) {
        return MKPP_ERROR_NULL_POINTER;
    }

    try {
        Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged> rates_view(
            rates_out, impl->num_cells, impl->num_reactions);

        for (std::size_t i = 0; i < impl->num_cells; ++i) {
            SolverKernelsType solver;
            auto sub_conc = Kokkos::subview(impl->species_conc, i, Kokkos::ALL());
            auto sub_rates = Kokkos::subview(rates_view, i, Kokkos::ALL());
            const double* jvals = impl->photolysis_rates.data() ? impl->photolysis_rates.data() + i * impl->num_photolysis : nullptr;
            solver.compute_rates(sub_conc, sub_rates, jvals);
        }
        return MKPP_SUCCESS;
    } catch (const std::exception& e) {
        impl->set_error(e.what());
        return MKPP_ERROR_INVALID_STATE;
    }
}

int mkpp_evaluate_jacobian(mkpp_handle_t handle, double* jac_out) {
    if (!handle || !jac_out) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    if (!impl->is_initialized) {
        return MKPP_ERROR_INVALID_STATE;
    }
    if (!impl->species_conc.data()) {
        return MKPP_ERROR_NULL_POINTER;
    }

    try {
        std::size_t non_zeros = 1822;
        Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::HostSpace, Kokkos::MemoryUnmanaged> jac_view(
            jac_out, impl->num_cells, non_zeros);

        for (std::size_t i = 0; i < impl->num_cells; ++i) {
            SolverKernelsType solver;
            auto sub_conc = Kokkos::subview(impl->species_conc, i, Kokkos::ALL());
            auto sub_jac = Kokkos::subview(jac_view, i, Kokkos::ALL());
            const double* jvals = impl->photolysis_rates.data() ? impl->photolysis_rates.data() + i * impl->num_photolysis : nullptr;
            solver.compute_jacobian(sub_conc, sub_jac, jvals);
        }
        return MKPP_SUCCESS;
    } catch (const std::exception& e) {
        impl->set_error(e.what());
        return MKPP_ERROR_INVALID_STATE;
    }
}

int mkpp_get_last_error(mkpp_handle_t handle, char* buffer, size_t buffer_len) {
    if (!handle || !buffer || buffer_len == 0) {
        return MKPP_ERROR_NULL_POINTER;
    }
    auto* impl = reinterpret_cast<mkpp_handle_impl*>(handle);
    std::strncpy(buffer, impl->last_error_msg.c_str(), buffer_len - 1);
    buffer[buffer_len - 1] = '\0';
    return MKPP_SUCCESS;
}

} // extern "C"
