/*
 * @file mkpp.h
 * @brief C11 ABI Header for MKPP Generated Chemical Mechanism: ts1
 *
 * Generated by MKPP AOT Compiler - DO NOT EDIT DIRECTLY.
 */

#ifndef MKPP_GENERATED_TS1_H
#define MKPP_GENERATED_TS1_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Return Status Codes */
#define MKPP_SUCCESS                  0
#define MKPP_ERROR_NULL_POINTER     -101
#define MKPP_ERROR_INVALID_HANDLE   -102
#define MKPP_ERROR_INVALID_ARGUMENT -103
#define MKPP_ERROR_INVALID_STATE    -104
#define MKPP_ERROR_CONVERGENCE      -105
#define MKPP_ERROR_NOT_FOUND        -106

/* Opaque Context Handle */
typedef struct mkpp_handle_s* mkpp_handle_t;

/* Mechanism Static Metadata Constants */
#define MKPP_NUM_SPECIES   210
#define MKPP_NUM_REACTIONS 547
#define MKPP_NUM_PHOTOLYSIS 0

/* Lifecycle Management */
int mkpp_create_handle(mkpp_handle_t* handle_out, size_t num_cells);
int mkpp_destroy_handle(mkpp_handle_t handle);
int mkpp_initialize(mkpp_handle_t handle);

/* Metadata & Dynamic Index Lookups */
int mkpp_get_species_count(mkpp_handle_t handle, size_t* count_out);
int mkpp_get_reaction_count(mkpp_handle_t handle, size_t* count_out);
int mkpp_get_photolysis_count(mkpp_handle_t handle, size_t* count_out);
int mkpp_get_species_index(mkpp_handle_t handle, const char* species_name, int* index_out);
int mkpp_get_photolysis_index(mkpp_handle_t handle, const char* photo_name, int* index_out);

/* Zero-Copy Host Memory Binding */
int mkpp_set_state_ptrs(mkpp_handle_t handle,
                        double* species_conc,
                        const double* temp,
                        const double* pressure,
                        const double* air_density);

int mkpp_set_photolysis_ptrs(mkpp_handle_t handle, const double* photolysis_rates);

int mkpp_set_aerosol_ptrs(mkpp_handle_t handle,
                         const double* relative_humidity,
                         const double* aerosol_surface_area);

/* Solver Computation Entry Points */
int mkpp_integrate(mkpp_handle_t handle, double dt);
int mkpp_evaluate_rates(mkpp_handle_t handle, double* rates_out);
int mkpp_evaluate_jacobian(mkpp_handle_t handle, double* jac_out);

/* Diagnostics & Error Inspection */
int mkpp_get_last_error(mkpp_handle_t handle, char* buffer, size_t buffer_len);

#ifdef __cplusplus
}
#endif

#endif /* MKPP_GENERATED_TS1_H */
